### PR TITLE
Added FTS5 to compile options

### PR DESCRIPTION
**Pull request by fabi321**

### CODE REVIEW

**Comment by justinclift** [comment]
Wonder if we should just copy across the same compile time options used for the Windows and macOS builds? eg [something like this](https://github.com/sqlitebrowser/sqlitebrowser/blob/967780d00b341cce2a67626b154a7249687abe32/installer/windows/nightly_build_scripts/win64build.bat#L70)

**Comment by fabi321** [comment]
I wondered why FTS 3/4 worked before, without those options

**Comment by justinclift** [comment]
> I wondered why FTS 3/4 worked before, without those options

As a wild guess, maybe they're enabled in the system provided SQLite?  That's the only thing springing to mind for me... :smile:

**Comment by gavinr** [comment]
I am running into the issue where FTS5 is not working on the deb build (https://github.com/sqlitebrowser/sqlitebrowser/issues/2761) ... it seems like this PR is the solution. Can we merge this?

**Pull request merged**
